In [1]:
import pandas as pd
import numpy as np
import tensorflow as tf

In [2]:
data = pd.read_csv("../../Datasets/Amazon_Product_Review_Dataset/amazon.csv")

In [3]:
data.head()

Unnamed: 0  reviewerName  overall  \
0           0           NaN        4   
1           1          0mie        5   
2           2           1K3        4   
3           3           1m2        5   
4           4  2&amp;1/2Men        5   

                                          reviewText  reviewTime  day_diff  \
0                                         No issues.  23-07-2014       138   
1  Purchased this for my device, it worked as adv...  25-10-2013       409   
2  it works as expected. I should have sprung for...  23-12-2012       715   
3  This think has worked out great.Had a diff. br...  21-11-2013       382   
4  Bought it with Retail Packaging, arrived legit...  13-07-2013       513   

   helpful_yes  helpful_no  total_vote  score_pos_neg_diff  \
0            0           0           0                   0   
1            0           0           0                   0   
2            0           0           0                   0   
3            0           0           0                   0   
4            0           0           0                   0   

   score_average_rating  wilson_lower_bound  
0                   0.0                 0.0  
1                   0.0                 0.0  
2                   0.0                 0.0  
3                   0.0                 0.0  
4                   0.0                 0.0

In [4]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4915 entries, 0 to 4914
Data columns (total 12 columns):
 #   Column                Non-Null Count  Dtype  
---  ------                --------------  -----  
 0   Unnamed: 0            4915 non-null   int64  
 1   reviewerName          4914 non-null   object 
 2   overall               4915 non-null   int64  
 3   reviewText            4914 non-null   object 
 4   reviewTime            4915 non-null   object 
 5   day_diff              4915 non-null   int64  
 6   helpful_yes           4915 non-null   int64  
 7   helpful_no            4915 non-null   int64  
 8   total_vote            4915 non-null   int64  
 9   score_pos_neg_diff    4915 non-null   int64  
 10  score_average_rating  4915 non-null   float64
 11  wilson_lower_bound    4915 non-null   float64
dtypes: float64(2), int64(7), object(3)
memory usage: 460.9+ KB


In [5]:
reviews = data["reviewText"]
labels = data["overall"]

In [37]:
[f"r" for r in reviews]

['r',
 'r',
 'r',
 'r',
 'r',
 'r',
 'r',
 'r',
 'r',
 'r',
 'r',
 'r',
 'r',
 'r',
 'r',
 'r',
 'r',
 'r',
 'r',
 'r',
 'r',
 'r',
 'r',
 'r',
 'r',
 'r',
 'r',
 'r',
 'r',
 'r',
 'r',
 'r',
 'r',
 'r',
 'r',
 'r',
 'r',
 'r',
 'r',
 'r',
 'r',
 'r',
 'r',
 'r',
 'r',
 'r',
 'r',
 'r',
 'r',
 'r',
 'r',
 'r',
 'r',
 'r',
 'r',
 'r',
 'r',
 'r',
 'r',
 'r',
 'r',
 'r',
 'r',
 'r',
 'r',
 'r',
 'r',
 'r',
 'r',
 'r',
 'r',
 'r',
 'r',
 'r',
 'r',
 'r',
 'r',
 'r',
 'r',
 'r',
 'r',
 'r',
 'r',
 'r',
 'r',
 'r',
 'r',
 'r',
 'r',
 'r',
 'r',
 'r',
 'r',
 'r',
 'r',
 'r',
 'r',
 'r',
 'r',
 'r',
 'r',
 'r',
 'r',
 'r',
 'r',
 'r',
 'r',
 'r',
 'r',
 'r',
 'r',
 'r',
 'r',
 'r',
 'r',
 'r',
 'r',
 'r',
 'r',
 'r',
 'r',
 'r',
 'r',
 'r',
 'r',
 'r',
 'r',
 'r',
 'r',
 'r',
 'r',
 'r',
 'r',
 'r',
 'r',
 'r',
 'r',
 'r',
 'r',
 'r',
 'r',
 'r',
 'r',
 'r',
 'r',
 'r',
 'r',
 'r',
 'r',
 'r',
 'r',
 'r',
 'r',
 'r',
 'r',
 'r',
 'r',
 'r',
 'r',
 'r',
 'r',
 'r',
 'r',
 'r',
 'r',
 'r',
 'r'

In [39]:
vocab_size = 10000
max_length = 100
text_vec_layer = tf.keras.layers.TextVectorization(vocab_size,standardize = "lower",output_sequence_length=max_length)
text_vec_layer.adapt([f"{r}" for r in reviews])
#encoded = text_vec_layer(review)[0]

In [40]:
text_vec_layer("r")

<tf.Tensor: shape=(100,), dtype=int64, numpy=
array([9306,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
          0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
          0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
          0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
          0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
          0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
          0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
          0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
          0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
          0], dtype=int64)>

In [41]:
text_vec_layer.get_vocabulary()[:100]

['',
 '[UNK]',
 'the',
 'i',
 'and',
 'to',
 'it',
 'a',
 'my',
 'this',
 'for',
 'card',
 'of',
 'in',
 'is',
 'with',
 'on',
 'have',
 'that',
 'was',
 'as',
 'works',
 'not',
 'but',
 'you',
 'so',
 'no',
 'memory',
 'sd',
 'phone',
 'sandisk',
 'great',
 'had',
 'use',
 'galaxy',
 'or',
 'one',
 'be',
 'can',
 'all',
 'bought',
 'just',
 'samsung',
 'at',
 'from',
 'very',
 'good',
 'if',
 'are',
 'would',
 'will',
 'about',
 "it's",
 'cards',
 'has',
 'any',
 'card.',
 'fast',
 'they',
 'when',
 'what',
 'more',
 'an',
 'storage',
 'using',
 'class',
 'got',
 'than',
 'these',
 'price',
 'get',
 'micro',
 'it.',
 'up',
 'me',
 'only',
 'like',
 'speed',
 'your',
 'out',
 'note',
 'other',
 'been',
 'gb',
 'worked',
 'music',
 'well',
 'used',
 'new',
 "i've",
 'work',
 'now',
 'buy',
 'into',
 'after',
 'do',
 '10',
 'much',
 'need',
 'card,']

In [42]:
text_vec_layer.vocabulary_size()

10000

In [43]:
reviews[1000:]

1000    Great price! works flawless with my note 3. I ...
1001    Called GoPro - they recommended this specific ...
1002    Gets the job done for my GoPro so that's good....
1003    This cards holds everything I can think to out...
1004    I was able to plug it in, use the format utili...
                              ...                        
4910    I bought this Sandisk 16GB Class 10 to use wit...
4911    Used this for extending the capabilities of my...
4912    Great card that is very fast and reliable. It ...
4913    Good amount of space for the stuff I want to d...
4914    I've heard bad things about this 64gb Micro SD...
Name: reviewText, Length: 3915, dtype: object

In [44]:
labels=np.array(data['overall'])

In [45]:
labels=labels.reshape(4915,1)

In [46]:
labels

array([[4],
       [5],
       [4],
       ...,
       [5],
       [5],
       [5]], dtype=int64)

In [47]:
from sklearn.preprocessing import OneHotEncoder
enc = OneHotEncoder();
enc.fit(labels)
output = pd.get_dummies(data['overall'])

In [48]:
output

1  2  3  4  5
0     0  0  0  1  0
1     0  0  0  0  1
2     0  0  0  1  0
3     0  0  0  0  1
4     0  0  0  0  1
...  .. .. .. .. ..
4910  1  0  0  0  0
4911  0  0  0  0  1
4912  0  0  0  0  1
4913  0  0  0  0  1
4914  0  0  0  0  1

[4915 rows x 5 columns]

In [54]:
X_train = tf.constant([f"{r}" for r in reviews[:4000]])
X_test = tf.constant([f"{r}" for r in reviews[4000:]])
y_train = tf.constant(output[:4000])
y_test = tf.constant(output[4000:])

In [64]:

X_test[1:5]

<tf.Tensor: shape=(4,), dtype=string, numpy=
array([b"Not much to say about the memory card. It's doing its job as expected. Bought mainly because it can store a lot information.",
       b"I gave away my last card to a friend who needed one.  After reading the reviews for this card I purchased it.  I seems quick enough for my needs and plenty of space.  I've never had a problem with SanDisk.  My go to company for all my Disk needs.",
       b'I bought this for my phone because the apps I was using were filling up the little space on the phone I had.  I had never changed out the card on a phone before but it was surprisingly easy and now I have tons of room for all my photos and apps and stuff.',
       b'I use this with my Samsung Galaxy 10.1 Tablet and it works Great. The SD card loads fast and I have had no issues.'],
      dtype=object)>

In [56]:
embed_size = 128
tf.random.set_seed(42)
model = tf.keras.Sequential([
    text_vec_layer,
    tf.keras.layers.Embedding(vocab_size, embed_size),
    tf.keras.layers.LSTM(128),
    tf.keras.layers.Dense(64, activation= 'relu'),
    tf.keras.layers.Dense(64, activation= 'relu'),
    tf.keras.layers.Dense(5, activation= 'softmax')
])

In [57]:
model.compile(loss="binary_crossentropy", optimizer="nadam", metrics=['accuracy'])

In [58]:
model.summary()

Model: "sequential_3"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 text_vectorization_4 (TextV  (None, 100)              0         
 ectorization)                                                   
                                                                 
 embedding_3 (Embedding)     (None, 100, 128)          1280000   
                                                                 
 lstm_2 (LSTM)               (None, 128)               131584    
                                                                 
 dense_9 (Dense)             (None, 64)                8256      
                                                                 
 dense_10 (Dense)            (None, 64)                4160      
                                                                 
 dense_11 (Dense)            (None, 5)                 325       
                                                      

In [61]:

model.fit(X_train,y_train, validation_data=(X_test,y_test),epochs=10,batch_size=24)

Epoch 1/10
167/167 [==============================] - 10s 57ms/step - loss: 0.1840 - accuracy: 0.8282 - val_loss: 0.2371 - val_accuracy: 0.7705
Epoch 2/10
167/167 [==============================] - 9s 55ms/step - loss: 0.1665 - accuracy: 0.8415 - val_loss: 0.2538 - val_accuracy: 0.7650
Epoch 3/10
167/167 [==============================] - 9s 52ms/step - loss: 0.1575 - accuracy: 0.8500 - val_loss: 0.2688 - val_accuracy: 0.7683
Epoch 4/10
167/167 [==============================] - 9s 55ms/step - loss: 0.1424 - accuracy: 0.8683 - val_loss: 0.2790 - val_accuracy: 0.7585
Epoch 5/10
167/167 [==============================] - 9s 54ms/step - loss: 0.1304 - accuracy: 0.8773 - val_loss: 0.2934 - val_accuracy: 0.7366
Epoch 6/10
167/167 [==============================] - 9s 54ms/step - loss: 0.1188 - accuracy: 0.8925 - val_loss: 0.2974 - val_accuracy: 0.7399
Epoch 7/10
167/167 [==============================] - 9s 57ms/step - loss: 0.1079 - accuracy: 0.9060 - val_loss: 0.3586 - val_accuracy: 0.748

In [62]:
y

NameError: name 'y' is not defined